name: Java CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '13' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: print Java version
      run: java -version
    - uses: wildfly/dep-tree-diff-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        modules: :java-lang-instrument-example
        deps-ok-label: No significant dependency changes
        deps-changed-label: Dependency changes
    - name: Build with Maven
      run: mvn clean package --file pom.xml
